const Data = [
  // Men's Jeans
  {
    id: 1,
    name: "Wrogn Men's Jeans",
    price: 350,
    category: 'Jeans',
    sex: 'Mens',
    img: 'WrognJ.png',
  },
  {
    id: 2,
    name: "Levis Mens's Jeans",
    price: 250,
    category: 'Jeans',
    sex: 'Mens',
    img: 'jeans2.jpg',
  },
  {
    id: 3,
    name: "Denim Mens's Jeans",
    price: 300,
    category: 'Jeans',
    sex: 'Mens',
    img: 'jeans3.jpg',
  },
  {
    id: 4,
    name: "Pepe Jeans Mens's Jeans",
    price: 270,
    category: 'Jeans',
    sex: 'Mens',
    img: 'jeans4.jpg',
  },
  {
    id: 5,
    name: "H&M Mens's T-shirt",
    price: 150,
    category: 'T-shirt',
    sex: 'Mens',
    img: 'tshirt1.jpg',
  },
  {
    id: 6,
    name: "Lee Mens's T-shirt",
    price: 160,
    category: 'T-shirt',
    sex: 'Mens',
    img: 'tshirt2.jpg',
  },
  {
    id: 7,
    name: "K-pop Mens's T-shirt",
    price: 140,
    category: 'T-shirt',
    sex: 'Mens',
    img: 'tshirt3.jpg',
  },
  {
    id: 8,
    name: "Wrogn Mens's T-shirt",
    price: 180,
    category: 'T-shirt',
    sex: 'Mens',
    img: 'tshirt4.jpg',
  },

  // Women's Dresses
  {
    id: 9,
    name: "Wrogn Women's Dress",
    price: 450,
    category: 'Dresses',
    sex: 'Womens',
    img: 'dress1.jpg',
  },
  {
    id: 10,
    name: "Levis Womens's Dress",
    price: 420,
    category: 'Dresses',
    sex: 'Womens',
    img: 'dress2.jpg',
  },
  {
    id: 11,
    name: "H&M Womens's Dress",
    price: 460,
    category: 'Dresses',
    sex: 'Womens',
    img: 'dress3.jpg',
  },
  {
    id: 12,
    name: "Pepe Jeans Womens's Dress",
    price: 430,
    category: 'Dresses',
    sex: 'Womens',
    img: 'dress4.jpg',
  },
  {
    id: 13,
    name: "Wrogn Womens's T-shirt",
    price: 170,
    category: 'T-shirt',
    sex: 'Womens',
    img: 'tshirt1.jpg',
  },
  {
    id: 14,
    name: "Levis Womens's T-shirt",
    price: 180,
    category: 'T-shirt',
    sex: 'Womens',
    img: 'tshirt2.jpg',
  },
  {
    id: 15,
    name: "H&M Womens's T-shirt",
    price: 160,
    category: 'T-shirt',
    sex: 'Womens',
    img: 'tshirt3.jpg',
  },
  {
    id: 16,
    name: "Pepe Jeans Womens's T-shirt",
    price: 200,
    category: 'T-shirt',
    sex: 'Womens',
    img: 'tshirt4.jpg',
  },

  // Kids' Items
  {
    id: 17,
    name: "Wrogn Kids Jeans",
    price: 100,
    category: 'Jeans',
    sex: 'Kids',
    img: 'kids-jeans1.jpg',
  },
  {
    id: 18,
    name: "H&M Kids Jeans",
    price: 90,
    category: 'Jeans',
    sex: 'Kids',
    img: 'kids-jeans2.jpg',
  },
  {
    id: 19,
    name: "Wrogn Kids T-shirt",
    price: 70,
    category: 'T-shirt',
    sex: 'Kids',
    img: 'kids-tshirt1.jpg',
  },
  {
    id: 20,
    name: "H&M Kids T-shirt",
    price: 75,
    category: 'T-shirt',
    sex: 'Kids',
    img: 'kids-tshirt2.jpg',
  },
];


export default Data;
